### ISSUE TITLE
Typo in the wiki of Bundles and Vecs

### ISSUE THREAD

**Issue by hadirkhan10** [freechipsproject/chisel3#1552]
**Type of issue**:  documentation

**Impact**: no functional change

**Development Phase**: proposal

**What is the use case for changing the behavior?** Better understanding of the documentation

**Comment by hadirkhan10** [comment]
Here is the fixed typo mistake for the wiki. 
https://github.com/hadirkhan10/chisel3-wiki

**Comment by seldridge** [comment]
Thanks for finding this and showing the correction @hadirkhan10! 

I manually applied your fix here: https://github.com/freechipsproject/chisel3/wiki/Bundles-and-Vecs/_compare/4977c335a2bba9dbec038b43d316aa330391ace3

As a note: the wiki is likely outdated and not well maintained. Some time back, the wiki content was migrated to the Chisel website so that the examples could be compiled (so we know they aren't broken): https://www.chisel-lang.org/chisel3/. The website *does* have your fix (via https://github.com/freechipsproject/www.chisel-lang.org/pull/42), so things are good to go on that side.

**Comment by hadirkhan10** [comment]
Alright thanks for pointing out @seldridge
