### ISSUE TITLE
API to walk through module scala instances

### ISSUE THREAD

**Issue by jchang0** [freechipsproject/chisel3#541]
I would like to be able to walk though a module hierarchy (for this particular application, the Scala instances) in order to collect information about the design (or in the future, generate monitor code to be bound later).
So an API to traverse through the module instances would be helpful.

**Comment by shunshou** [comment]
Do you want this to be done in Chisel or in Firrtl? I've requested something similar to this for the purposes of auto-generating some clock constraint information at the Firrtl level. Assuming the module name is unique, @albert-magyar wrote a cutesy analysis thing that can map the module name to its absolute instance path. (If the module name is not unique, it'll get all instance paths to that module). I'm pretty sure @jackkoenig @azidar are aware of how powerful something like this can be, and really, I think this is where you can really exercise Firrtl potential...

**Comment by jackkoenig** [comment]
I think there are reasons you would want it in both. In Firrtl for obvious
reasons, but also in Chisel it can be nice to be able to inspect the actual
Chisel Scala objects.

On Thu, Mar 2, 2017 at 3:16 PM Angie Wang <notifications@github.com> wrote:

Do you want this to be done in Chisel or in Firrtl? I've requested
something similar to this for the purposes of auto-generating some clock
constraint information at the Firrtl level. Assuming the module name is
unique, @albert-magyar <https://github.com/albert-magyar> wrote a cutesy
analysis thing that can map the module name to its absolute instance path.
(If the module name is not unique, it'll get all instance paths to that
module). I'm pretty sure @jackkoenig <https://github.com/jackkoenig> @azidar
<https://github.com/azidar> are aware of how powerful something like this
can be, and really, I think this is where you can really exercise Firrtl
potential...

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/ucb-bar/chisel3/issues/541#issuecomment-283784126>, or mute
the thread

**Comment by jchang0** [comment]
For this particular need I'm currently encountering, in Chisel (I want to access the LazyModule parameters so that I can create a separate breakout unit level tester with the same parameters as the final instantiation).  But I've talked to jack about firrtl passes also for other purposes in the past also.

**Comment by ducky64** [comment]
Related: #414

**Comment by azidar** [comment]
This is implemented in #1077 !
