### ISSUE TITLE
[RFC] API Documentation Improvements

### ISSUE THREAD

**Issue by seldridge** [freechipsproject/chisel3#872]
**Type of issue**: other enhancement

**Impact**: no functional change

**Development Phase**: proposal

**Other information**
 

**What is the current behavior?**

The API documentation could be improved substantially. Currently users are working across multiple different sources of stale information (Chisel cheatsheet, DAC 2012 paper) or current information (the published API scaladoc/unidoc documentation). However, there are two major problems with current information:

- things which should be exhaustively documented are not
- things which a user has no business using, e.g., `do_apply`, appear along with everything else

With this in place, all documentation _should_ collapse to the published API scaladoc/unidoc with the exception of tutorials. Users then have one source of information.

**What is the expected behavior?**

1. Document all the things
2. Hide things as best as we can that a user shouldn't be using (via low priority groups)

I have an example of using groups in https://github.com/seldridge/chisel3/commit/336ab3f06c17a77d6436b8bd91456b53c07dba9b. We can use this to push all advanced things, e.g., `do_apply`, as the last thing a user sees with a strong warning to ignore these. The rest of it is elbow grease.

Example of a low priority group:
![2018-08-10-205854_1035x1059_scrot](https://user-images.githubusercontent.com/1018530/43986533-3871d7f8-9ce0-11e8-87ad-ba58f9f138fc.png)

One suggestion for an example of documentation: https://github.com/freechipsproject/chisel3/blob/master/src/main/scala/chisel3/util/experimental/BoringUtils.scala#L15. 

**Other things**

- Is there any good way to hide the group? (Or make it look like `@deprecated`?)
- Can we use `@inheritdoc` to cut down on boilerplate?
- I've assumed that users want the scaladoc/unidoc as the main source of documentation. This makes sense, yes?
- Often an example that I write in some scaladoc is the exact same thing that I use in a test. Is there anyway to avoid having to write this twice?

**Comment by ducky64** [comment]
I like the example!

I think that at least as long as the do_* methods are in the source (instead of generated by macros), it makes sense to generate scaladoc, with a note explaining why they exist, though possibly with the group collapsed by default if possible.

Side note: do you know how ScalaDoc interacts with macros that generate methods?

I agree with the principle of one source of information, though I also find cheatsheets useful, both for the print-ready formatting and the prioritization of information. But we would need to keep it up-to-date, and we should deprecate older docs.

We should also keep an index of up-to-date documentation, either on the GitHub (which doesn't even have a link to the generator bootcamp, but links to chisel-tutorial) or the website (should the ScalaDoc link be under the "learn" tab? - it also has the DAC paper which is probably way outdated now; it might be worth keeping a link for historical purposes, but it probably shouldn't be front-and-center).

**Comment by seldridge** [comment]
I'll work up a full PR for all the `do_` methods.

> Side note: do you know how ScalaDoc interacts with macros that generate methods?

I think that this just doesn't work. I found this [SO hit](https://stackoverflow.com/questions/42684101/scaladoc-generation-fails-when-referencing-methods-generated-by-annotation-macro). Running the attached GitHub project results in the shown behavior: methods generated by macros just fail to be found.

There may be some approach to not do macro expansion (e.g., `-Ymacro-expand:none`) that would have the added benefit of preventing these from showing up in the scaladoc.

Re: cheatsheet: One approach would be to include that as a large example on the landing page of the scaladoc API.

Keeping things up-to-date is a big issue. I don't have a good solution to that, but I keep thinking that pulling examples from the scaladoc tests would at least make sure that things will run. Have to think on that.

**Comment by seldridge** [comment]
The primary aim of this is closed with #873. Other documentation improvements will/should be a separate issue.
