### ISSUE TITLE
Where is import scala.reflect.macros.blackbox.Context?

### ISSUE THREAD

**Issue by kai413629305** [freechipsproject/chisel3#969]
In chisel3/chiselFrontend/src/main/scala/chisel3/internal/SourceInfo.scala,Where is import scala.reflect.macros.blackbox.Context in ninth line?

**Comment by ucbjrl** [comment]
I'm not sure I understand your question, and it's been some time since this question was posed, but `scala.reflect.macros.blackbox.Context` appears to be in the Scala reflect library at [`scala/reflect/macros/blackbox/Context.scala`](https://github.com/scala/scala/blob/2.12.x/src/reflect/scala/reflect/macros/blackbox/Context.scala) (at least for Scala 2.12.10).
